### ISSUE TITLE
关于通过请求头（x-pjax）来分别输出文件部分

### ISSUE THREAD

**Issue by xiaoweibaniu** [Rocket1184/BlogNode#1]
![image](https://cloud.githubusercontent.com/assets/13979614/20095094/04433f20-a5df-11e6-88d1-5e1b3c019613.png)
想问下这一块儿应该具体如何输出。关于部分输出和整体输出的操作。

在你的项目中也找了，但是没有找到这一部分代码。求指点。。万分感谢！

**Comment by rocka** [comment]
现在项目里的代码和之前的代码差别已经很大了，找不到也正常   = =
- 如果识别到pjax请求头，那么就用`fs.readFile`读取文件内容，然后直接`response.end(data)`发出去
- 否则，先读取文件内容，再把内容替换到阅读页面的模板里面，然后把替换后的页面~~就是字符串~~发出去

**Comment by xiaoweibaniu** [comment]
你这里的读取文件内容，是不是意味着这个文件无法做为入口文件直接访问，都是要通过阅读页面进入的。

不管是哪种请求，都要去读取文件，这样是不是工作量太大了！使用模板引擎应该能更方便吧

**Comment by rocka** [comment]
是的 我也有这样想过。先用文件存储来过渡，最终我是想换到数据库的
